import face_recognition
from PIL import Image, ImageDraw
import cv2
import imutils
from imutils.video import VideoStream
import numpy as np
# from  simple_facerec import SimpleFacerec

cap = cv2.VideoCapture("rtsp://admin:belprom1@192.168.1.64:554/out.h264")


# replace this with the url generated by the Wyze app
rtsp_url = "rtsp://admin:belprom1@192.168.1.64:554/out.h264"

vs = VideoStream(rtsp_url).start()

while True:
    frame = vs.read()

    if frame is None:
        continue

    frame = imutils.resize(frame, width=640)

    cv2.imshow('WyzeCam', frame)

    key = cv2.waitKey(1) & 0xFF

    if key == ord('q'):
        break

cv2.destroyAllWindows()
vs.stop()
# def recognition():
#    pass

#
# if __name__ == "__main__":
#     recognition()
